using System.ComponentModel;

namespace BrinquedotecaPUC.Web.CrossCutting.Enumerators
{
    public enum EstadosEnum
    {
        [Description("AC")]
        AC,
        [Description("AL")]
        AL,
        [Description("AM")]
        AM,
        [Description("AP")]
        AP,
        [Description("BA")]
        BA,
        [Description("CE")]
        CE,
        [Description("DF")]
        DF,
        [Description("ES")]
        ES,
        [Description("GO")]
        GO,
        [Description("MA")]
        MA,
        [Description("MG")]
        MG,
        [Description("MS")]
        MS,
        [Description("MT")]
        MT,
        [Description("PA")]
        PA,
        [Description("PB")]
        PB,
        [Description("PE")]
        PE,
        [Description("PI")]
        PI,
        [Description("PR")]
        PR,
        [Description("RJ")]
        RJ,
        [Description("RN")]
        RN,
        [Description("RO")]
        RO,
        [Description("RR")]
        RR,
        [Description("RS")]
        RS,
        [Description("SC")]
        SC,
        [Description("SE")]
        SE,
        [Description("SP")]
        SP,
        [Description("TO")]
        TO
    }
}
